#!/usr/bin/env bash
# Copyright (c) 2023 rM-self-serve
# SPDX-License-Identifier: MIT

webinterface_persist_ip_version='v2.0'

ip_cmd="ip addr change 10.11.99.1/32 dev usb0"

main() {
	case "$@" in
	'-h' | '--help' | '')
		cli_info
		;;
	'apply-prstip')
		apply_prstip
		;;
	'revert-prstip')
		revert_prstip
		;;
	*)
		echo 'input not recognized'
		cli_info
		;;
	esac
	true
}

cli_info() {
	echo -e "${GREEN}webinterface-persist-ip ${webinterface_persist_ip_version}${NC}"
	echo ''
	echo 'This simple program will ensure the web-interface is internally'
	echo "accessible at 10.11.99.1:80 after disconnecting the usb cord."
	echo 'Source+Docs: https://github.com/rM-self-serve/webinterface-persist-ip'
	echo ''
	echo -e "${CYAN}USAGE:${NC}"
	echo '  webinterface-persist-ip [OPTIONS]'
	echo ''
	echo -e "${CYAN}COMMANDS:${NC}"
	echo '  apply-prstip        Apply persist ip modification'
	echo '  revert-prstip       Revert persist ip modification'
	echo ''
	echo -e "${CYAN}OPTIONS:${NC}"
	echo '  -h, --help        Show help'
}

vars_prstip() {
	target_file='/etc/ifplugd/ifplugd.action'
	target_content=$(cat $target_file)

	stop_line=$(echo "$target_content" | grep -n 'systemctl stop' | cut -d : -f 1)
	total_line=$(echo "$target_content" | wc -l)

	tmp_file="/home/root/.webint-persist-ip.ifplugd.action.tmp"
}

is_action_moded() {
	echo "$1" | grep -qhE "$ip_cmd"
}

apply_prstip() {
	vars_prstip

	echo "Applying webint-upldbtn will edit:"
	echo "/etc/ifplugd/ifplugd.action"
	echo ""

	read -r -p "Would you like to continue? [y/N] " response
	case "$response" in
	[yY][eE][sS] | [yY])
		apply_prstip_act
		;;
	*)
		echo "Cancel"
		;;
	esac

}

apply_prstip_act() {
	if is_action_moded "$target_content"; then
		echo "Persist ip already applied"
		exit
	fi

	root_line="$((stop_line + 1))"
	[[ -f $tmp_file ]] && rm "$tmp_file"
	{
		echo "$target_content" | sed -n 1,"$stop_line"p
		echo "    $ip_cmd"
		echo "$target_content" | sed -n "$root_line","$total_line"p
	} >"$tmp_file"

	chmod +x "$tmp_file" && cp "$tmp_file" "$target_file"
	echo "Persist ip applied"
}

revert_prstip() {
	vars_prstip

	read -r -p "Would you like to revert persist ip? [y/N] " response
	case "$response" in
	[yY][eE][sS] | [yY])
		revert_prstip_act
		;;
	*)
		echo "Cancel"
		;;
	esac
}

revert_prstip_act() {
	if ! is_action_moded "$target_content"; then
		echo "Persist ip has not been applied"
		exit
	fi

	root_line="$((stop_line + 2))"
	[[ -f "$tmp_file" ]] && rm "$tmp_file"
	{
		sed -n 1,"$stop_line"p "$target_file"
		sed -n "$root_line","$total_line"p "$target_file"
	} >"$tmp_file"
	chmod +x "$tmp_file" && mv "$tmp_file" "$target_file"
	echo "Persist ip reverted"

}

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

main "$@"
