#!/usr/bin/env bash
# Copyright (c) 2023 rM-self-serve
# SPDX-License-Identifier: MIT

webinterface_persist_ip_version='v2.0'

ip_cmd="ip addr change 10.11.99.1/32 dev usb0"

main() {
	case "$@" in
	'-h' | '--help' | '')
		cli_info
		;;
	'apply')
		apply
		;;
	'revert')
		revert
		;;
	*)
		echo 'input not recognized'
		cli_info
		;;
	esac
	true
}

cli_info() {
	echo -e "${GREEN}webinterface-persist-ip ${webinterface_persist_ip_version}${NC}"
	echo ''
	echo 'This simple program will ensure the web-interface is internally'
	echo "accessible at 10.11.99.1:80 after disconnecting the usb cord."
	echo 'Source+Docs: https://github.com/rM-self-serve/webinterface-persist-ip'
	echo ''
	echo -e "${CYAN}USAGE:${NC}"
	echo '  webinterface-persist-ip [OPTIONS]'
	echo ''
	echo -e "${CYAN}COMMANDS:${NC}"
	echo '  apply        Apply persist ip modification'
	echo '  revert       Revert persist ip modification'
	echo ''
	echo -e "${CYAN}OPTIONS:${NC}"
	echo '  -h, --help        Show help'
}

vars() {
	indx_file='/etc/ifplugd/ifplugd.action'
	ndx_content=$(cat $indx_file)

	stop_line=$(echo "$ndx_content" | grep -n 'systemctl stop' | cut -d : -f 1)
	total_line=$(echo "$ndx_content" | wc -l)

	tmp_file="/tmp/webint-persist-ip.tmp.ifplugd.action"
}

is_action_moded() {
	if echo "$1" | grep -qhE "$ip_cmd"; then
		return 0
	else
		return 1
	fi
}

apply() {
	vars

	echo "Applying webint-upldbtn will edit:"
	echo "/etc/ifplugd/ifplugd.action"
	echo ""

	read -r -p "Would you like to continue? [y/N] " response
	case "$response" in
	[yY][eE][sS] | [yY])
		apply_index
		;;
	*)
		echo "Cancel"
		;;
	esac

}

apply_index() {
	if is_action_moded "$ndx_content"; then
		echo "Persist ip already applied"
		exit
	fi

	root_line="$((stop_line + 1))"
	[[ -f $tmp_file ]] && rm "$tmp_file"
	{
		echo "$ndx_content" | sed -n 1,"$stop_line"p
		echo "    $ip_cmd"
		echo "$ndx_content" | sed -n "$root_line","$total_line"p
	} >"$tmp_file"

	cp "$tmp_file" "$indx_file"
	chmod +x "$indx_file"
	echo "Persist ip applied"
}

revert() {
	vars

	read -r -p "Would you like to revert persist ip? [y/N] " response
	case "$response" in
	[yY][eE][sS] | [yY])
		revert_index
		;;
	*)
		echo "Cancel"
		;;
	esac
}

revert_index() {
	if ! is_action_moded "$ndx_content"; then
		echo "Persist ip has not been applied"
		exit
	fi

	root_line="$((stop_line + 2))"
	[[ -f "$tmp_file" ]] && rm "$tmp_file"
	{
		sed -n 1,"$stop_line"p "$indx_file"
		sed -n "$root_line","$total_line"p "$indx_file"
	} >"$tmp_file"
	mv "$tmp_file" "$indx_file"
	chmod +x "$indx_file"
	echo "Persist ip reverted"

}

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

main "$@"
